# Generated by Django 5.0 on 2023-12-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_tag_gametag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="end_date",
        ),
        migrations.AddField(
            model_name="poll",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
