# Generated by Django 5.0 on 2023-12-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_remove_poll_end_date_poll_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="weight",
            field=models.IntegerField(default=1),
        ),
    ]
