# Generated by Django 5.0.2 on 2024-08-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_vote_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
