# Generated by Django 5.1.5 on 2025-01-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_game_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="weight",
        ),
        migrations.AddField(
            model_name="gamevote",
            name="weight",
            field=models.IntegerField(default=1),
        ),
    ]
