# Generated by Django 5.1.5 on 2025-07-27 15:17

from django.conf import settings
from django.db import migrations, models


def migrate_tags(apps, schema_editor):
    Game = apps.get_model("polls", "Game")
    GameTag = apps.get_model("polls", "GameTag")

    for gametag in GameTag.objects.all():
        game = gametag.game
        tag = gametag.tag
        game.tags.add(tag)


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_remove_gamevote_weight"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="tags",
            field=models.ManyToManyField(to="polls.tag"),
        ),
        migrations.RunPython(migrate_tags),
        migrations.AddField(
            model_name="gamevote",
            name="sub_vote",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="poll",
            name="title",
            field=models.CharField(default="FILLME", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="gamevote",
            unique_together={("game", "vote")},
        ),
        migrations.AlterUniqueTogether(
            name="pollblock",
            unique_together={("poll", "person")},
        ),
    ]
