# Generated by Django 5.1.5 on 2025-07-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_game_tags_gamevote_sub_vote_alter_poll_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="steam_id",
            field=models.BigIntegerField(),
        ),
        migrations.DeleteModel(
            name="GameTag",
        ),
    ]
