# Generated by Django 5.1.5 on 2025-07-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0010_alter_game_steam_id_delete_gametag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamevote",
            name="sub_vote",
        ),
    ]
