# Generated by Django 5.1.5 on 2025-07-31 19:38

from django.db import migrations, models


def migrate_closed_to_status(apps, schema_editor):
    Poll = apps.get_model("polls", "Poll")
    for poll in Poll.objects.all():
        poll.status = "finished" if poll.closed else "closed"
        poll.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0011_remove_gamevote_sub_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активно"),
                    ("closed", "Голосование окончено"),
                    ("finished", "Итоги подведены"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.RunPython(migrate_closed_to_status),
        migrations.RemoveField(
            model_name="poll",
            name="closed",
        ),
        migrations.AddField(
            model_name="vote",
            name="sub_vote",
            field=models.BooleanField(default=False),
        ),
    ]
