# Generated by Django 5.2.4 on 2025-08-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0012_remove_poll_closed_poll_status_vote_sub_vote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="start_date",
        ),
    ]
